# Generated by Django 5.1.6 on 2026-06-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Sarlavhasi", max_length=255)),
                (
                    "full_comment",
                    models.CharField(help_text="to'liq komment", max_length=1000),
                ),
            ],
        ),
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="Komentator ismi", max_length=255),
                ),
                (
                    "phone_number",
                    models.CharField(help_text="Telefon raqami", max_length=12),
                ),
                ("written_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
